FROM jjanzic/docker-python3-opencv:latest

ENV POETRY_VERSION=1.1.13

WORKDIR /app

RUN pip install "poetry==$POETRY_VERSION"

COPY ./ ./

RUN apt-get update -qy && \
    apt-get install -qy libzbar0 && \
	rm -rf /var/lib/apt/lists/* && \
    apt-get -qq autoremove && \
    apt-get -qq clean

RUN poetry config virtualenvs.create false && \
    poetry config virtualenvs.in-project false && \
    poetry install --no-dev

ENV PORT 8001

CMD streamlit run app/1_Food_to_Bank.py --server.port $PORT --server.address 0.0.0.0
