FROM python:3.8.7

ENV POETRY_VERSION=1.1.13

WORKDIR /app

RUN pip install "poetry==$POETRY_VERSION"

RUN apt-get update -qy && \
    apt-get install -qy libzbar0 ffmpeg libgl1 && \
	rm -rf /var/lib/apt/lists/* && \
    apt-get -qq autoremove && \
    apt-get -qq clean

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false && \
    poetry config virtualenvs.in-project false && \
    poetry install --no-dev

COPY ./ ./

ENV PORT 8001
CMD streamlit run app/1_Barcode_Scanner.py --server.port $PORT --server.address 0.0.0.0
