[tool.poetry]
name = "food-pov-hack"
version = "0.1.0"
description = ""
authors = ["Team 6 <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "^0.78.0"
uvicorn = "^0.17.6"
pytest = "^7.1.2"

[tool.poetry.dev-dependencies]
typer = "^0.4.1"
pytest = "^7.1.2"
isort = "^5.10.1"
flake8 = "^4.0.1"
black = "^22.3.0"
pytest-asyncio = "^0.18.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
verbose = true
skip-string-normalization = true
fast = true
