# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Install Poetry Action
      # You may pin to the exact commit or the version.
      # uses: snok/install-poetry@2bf112a0f6979928eb6b011f39700db589c5961e
      uses: snok/install-poetry@v1.3.1
      with:
        # The Poetry version to install
        version: 3.7 # default is latest
    - name: Lint 
      run: |
        make lint_service 
    - name: Test with pytest
      run: |
        make test_service
